### ISSUE TITLE
Remote user is missing R/W access to /dev/uinput (edit: uinput is missing)

### ISSUE THREAD

**Issue by graphpivot** [kokoko3k/ssh-rdp#11] opened 2022-01-10 21:20 UTC
Hi, 

I have a PC (client, with Ubuntu 20.04) at home and a remote VPS (with Ubuntu 20.04). I have added the users ob both machines to the input group, but I still get  the warning:

`Remote user is missing R/W access to /dev/uinput`

after I establish a SSH connection to the remote user.

Can you help?
Cheers!

**Comment by kokoko3k** [comment] 2022-01-10 22:35
Yes, you missed a step:

Special requirements for input forwarding:
    * Local user need to access files under /dev/input,
      so make sure it is in the input group.
    ***Remote user need access to special device /dev/uinput
      You can do that by install the provided 70-uinput.rules 
      into /etc/udev/rules.d on the remote side and reboot it.**

**Comment by graphpivot** [comment] 2022-01-10 22:58
Thank you for your fast answer. Here is the output from the remove server:

```
cat /etc/udev/rules.d/70-uinput.rules
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", OPTIONS+="static_node=uinput"
```
Have I missed something here?

**Comment by kokoko3k** [comment] 2022-01-10 23:00
It seems right.
Do you rebooted it to apply the rule?

**Comment by graphpivot** [comment] 2022-01-10 23:06
I have just rebooted the remote machine. Unfortunately I have still the warnings:

```
[WW] Remote user is missing R/W access to /dev/uinput
[WW] which is needed to forward input devices.
[WW] Do you want to continue anyway (not recommended) (y/n) ?
```

**Comment by kokoko3k** [comment] 2022-01-11 06:38
Taking for granted that if you proceed you have not control over the remote machine, could you please check if anything discussed in the following link is relevant for you?
(check for remote permissions, check if module uinput is loaded and so on)
https://github.com/chrippa/ds4drv/issues/93

**Comment by graphpivot** [comment] 2022-01-11 08:36
Thank you for the suggestion. Here the permissions:

```
ls -la /etc/udev/rules.d/
total 12
drwxr-xr-x 2 root root 4096 Jan  1 18:11 .
drwxr-xr-x 4 root root 4096 Jan 10 23:04 ..
-rw-r--r-- 1 root root  114 Jan  1 18:11 70-uinput.rules
```
I have also tried 
```
udevadm control --reload-rules
udevadm trigger
```
as root, but I get the same warning. 

When I proceed after the warning I get:

```
[OK] Checked required executables

[..] Checking input devices...
[OK] Device ready       : HP USB Business Slim Keyboard
     add event device for HP USB Business Slim Keyboard: event3
     add event device for HP USB Business Slim Keyboard: event4
     add event device for HP USB Business Slim Keyboard: event5
     add event device for HP USB Business Slim Keyboard: event6
[OK] Device ready       : Logitech MX Vertical
     add event device for Logitech MX Vertical: event7
[..] Reading hotkey file /home/USER/.config/ssh-rdp.input.hk.config
[OK] GRAB_HOTKEY=30
[OK] FULLSCREENSWITCH_HOTKEY=16

[..] Setting up input loop and forwarding devices
     forward input from device event3...
     forward input from device event4...
     forward input from device event5...
     forward input from device event6...
     forward input from device event7...

[..] Starting netevent daemon with script /tmp/nescript5027
added device mykbd1
added hotkey 1:30:1 for device 0
added on-'grab-changed' command
added hotkey 1:30:0 for device 0
added hotkey 1:16:1 for device 0
added hotkey 1:16:0 for device 0
added device dev2
added device dev3
added device mykbd4
added hotkey 1:30:1 for device 3
replaced on-'grab-changed' command
added hotkey 1:30:0 for device 3
added hotkey 1:16:1 for device 3
added hotkey 1:16:0 for device 3
added device dev5
added output myremote

[..] Trying to connect to USER@REMOTE-IP:22
     and stream display :0
     with size AUTO and offset: +0,0

[..] Guessing audio capture device
error: cannot find uinput device node
interrupted
[WW] Guessed audio capture source: auto_null.monitor

[..] Guessing remote resolution
xdpyinfo:  unable to open display ":0.0".

[..] Start audio streaming...
[..] Start video streaming...
[file] Reading from stdin...
[NULL @ 0x558c3d917e80] Requested output format 'x11grab' is not a suitable output format
:0.0+0,0: Invalid argument
Failed to recognize file format.


Exiting... (Errors when loading file)
bash: line 1:  8483 Killed                  /tmp/ffmpeg5027 -v quiet -nostdin -loglevel warning -y -f pulse -ac 2 -fragment_size 1024 -i auto_null.monitor -filter_complex amix=inputs=1 -b:a 128k -acodec libopus -vbr off -application lowdelay -f nut -
pipe:: Invalid data found when processing input
interrupted
shutting down
```

**Comment by kokoko3k** [comment] 2022-01-11 09:32
Remote: what is the output of:
```ls -la /dev/uinput```

**Comment by graphpivot** [comment] 2022-01-11 09:44
```
ls -la /dev/uinput
ls: cannot access '/dev/uinput': No such file or directory
```

**Comment by kokoko3k** [comment] 2022-01-13 14:35
Somehow the kernel installed by your vps is missing the uinput module, have you checked the link i provided?
Depending on your remote distribution, you've to find an automated way to load it.
Manually, as root, you can issue "modprobe uninput", then maybe you've to restart the graphic environment.

Closing here, because the problem is not by ssh-rdp side, maybe i can write a more meaningful error message.

**Closed as completed by kokoko3k** 2022-01-13 14:35 UTC
